import hashlib
import json
import time
from typing import Dict, Any, List, Optional


class UniversalBasicComputeEngine:
    """
    Bare-Metal Universal Basic Compute Engine (UBC-v1.0).
    Provides a zero-rent, autonomous yield engine that pairs local thermodynamic
    hardware capacity (power/battery) with ambient stigmergic task environments.

    Replaces centralized welfare dependencies and platform tollbooths with direct,
    thermodynamic edge yield generated by local silicon.
    """

    def __init__(self, node_id: str, hardware_power_draw_watts: float):
        self.node_id = node_id
        self.power_draw_watts = hardware_power_draw_watts
        self.state_ledger: Dict[str, Dict[str, Any]] = {}

    def calculate_net_yield_cents(
        self,
        duration_hours: float,
        electricity_rate_cents_per_kwh: float,
        gross_reward_cents: int
    ) -> int:
        """
        Calculates net yield after deducting local thermodynamic OpEx (kWh consumed).
        """
        energy_consumed_kwh = (self.power_draw_watts / 1000.0) * duration_hours
        power_cost_cents = energy_consumed_kwh * electricity_rate_cents_per_kwh
        net_yield = float(gross_reward_cents) - power_cost_cents
        return int(net_yield)

    def evaluate_task_execution(
        self,
        task_schema: Dict[str, Any],
        electricity_rate_cents_per_kwh: float
    ) -> Dict[str, Any]:
        """
        Evaluates whether an ambient stigmergic task meets local yield constraints.
        """
        task_id = task_schema.get("task_id", "")
        duration_hours = task_schema.get("estimated_duration_hours", 0.0)
        gross_reward_cents = task_schema.get("reward_cents", 0)

        net_yield = self.calculate_net_yield_cents(
            duration_hours,
            electricity_rate_cents_per_kwh,
            gross_reward_cents
        )

        executable = net_yield > 0
        return {
            "task_id": task_id,
            "executable": executable,
            "net_yield_cents": net_yield,
            "power_draw_watts": self.power_draw_watts,
            "duration_hours": duration_hours
        }

    def commit_task_yield(
        self,
        task_id: str,
        execution_payload: str,
        expected_hash: str
    ) -> bool:
        """
        Commits state transition upon successful deterministic execution,
        unlocking the micro-payment settlement hash.
        """
        computed_hash = hashlib.sha256(execution_payload.encode("utf-8")).hexdigest()
        if computed_hash != expected_hash:
            return False

        self.state_ledger[task_id] = {
            "node_id": self.node_id,
            "execution_payload": execution_payload,
            "proof_hash": computed_hash,
            "timestamp": int(time.time()),
            "status": "SETTLED"
        }
        return True


def run_ubc_proof() -> bool:
    """
    Verification proof for Universal Basic Compute Engine.
    """
    engine = UniversalBasicComputeEngine(node_id="node-edge-77", hardware_power_draw_watts=250.0)

    task_schema = {
        "task_id": "ubc-task-101",
        "estimated_duration_hours": 2.0,
        "reward_cents": 150  # $1.50 payout
    }

    # Electricity cost at 12 cents per kWh -> 0.5 kWh consumed = 6 cents cost.
    eval_result = engine.evaluate_task_execution(task_schema, electricity_rate_cents_per_kwh=12.0)
    assert eval_result["executable"] is True
    assert eval_result["net_yield_cents"] == 144  # 150 - 6 = 144 cents net

    payload = "UBC_STATE_EXECUTION_VERIFIED_ZERO_RENT"
    target_hash = hashlib.sha256(payload.encode("utf-8")).hexdigest()

    committed = engine.commit_task_yield(
        task_id="ubc-task-101",
        execution_payload=payload,
        expected_hash=target_hash
    )
    assert committed is True
    return True


if __name__ == "__main__":
    if run_ubc_proof():
        print("UBC_ENGINE_PROOF_PASSED")
